name: Continuous Integration

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  trunk:
    name: Trunk
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
